/**
 * A page's `icon` is a single string so it can live in one database column and
 * travel over IPC unchanged. It carries three kinds of value, told apart by a
 * scheme prefix:
 *
 *   `😀`               an emoji (or any short literal text) — the original
 *                      format, so pages written before the other two kinds
 *                      existed keep working with no migration
 *   `lucide:Star`      a named icon from the bundled lucide set
 *   `file:<name>`      an image the user uploaded, stored under the app's
 *                      `page-icons` directory
 *
 * Anything unrecognised is treated as emoji/text rather than discarded, so a
 * value this build doesn't understand still renders as *something*.
 *
 * Keep this file dependency-free: the main process, the preload bridge and the
 * renderer all import it.
 */

export const LUCIDE_ICON_PREFIX = 'lucide:'
export const FILE_ICON_PREFIX = 'file:'

/** Custom scheme the main process serves uploaded icon files on. */
export const ICON_SCHEME = 'graphite-icon'

export type ParsedIcon =
  | { kind: 'emoji'; text: string }
  | { kind: 'lucide'; name: string; color: IconColor | null }
  | { kind: 'file'; file: string }

/**
 * The colours a lucide icon can be tinted with. Kept as names rather than raw
 * hex in the stored value so the palette can be restyled later — and so a
 * stored icon can never smuggle arbitrary CSS into a `style` attribute.
 *
 * `null` (no suffix) means the icon inherits the surrounding text colour,
 * which is what the pickers show as "Default".
 */
export const ICON_COLORS = {
  gray: '#8b8b8b',
  brown: '#a1663b',
  orange: '#e07b39',
  yellow: '#d4a72c',
  green: '#3f9d58',
  blue: '#3b82f6',
  purple: '#9b5de5',
  pink: '#e0559b',
  red: '#e0555a'
} as const

export type IconColor = keyof typeof ICON_COLORS

export function isIconColor(value: string): value is IconColor {
  return Object.prototype.hasOwnProperty.call(ICON_COLORS, value)
}

/**
 * Uploaded file names are generated by the main process, but they arrive back
 * from the database as plain strings — validate before they ever reach a path
 * join or a URL, so a hand-edited row can't walk out of the icons directory.
 */
const FILE_NAME_PATTERN = /^[A-Za-z0-9_-]+\.[A-Za-z0-9]+$/

export function isValidIconFileName(name: string): boolean {
  return FILE_NAME_PATTERN.test(name)
}

export function parseIcon(icon: string | null | undefined): ParsedIcon | null {
  if (!icon) return null

  if (icon.startsWith(LUCIDE_ICON_PREFIX)) {
    // `lucide:Star` or `lucide:Star:blue` — icon names never contain a colon.
    const [name, color] = icon.slice(LUCIDE_ICON_PREFIX.length).split(':')
    if (!name) return null
    return { kind: 'lucide', name, color: color && isIconColor(color) ? color : null }
  }

  if (icon.startsWith(FILE_ICON_PREFIX)) {
    const file = icon.slice(FILE_ICON_PREFIX.length)
    return isValidIconFileName(file) ? { kind: 'file', file } : null
  }

  return { kind: 'emoji', text: icon }
}

export function lucideIconValue(name: string, color?: IconColor | null): string {
  return color ? `${LUCIDE_ICON_PREFIX}${name}:${color}` : `${LUCIDE_ICON_PREFIX}${name}`
}

export function fileIconValue(fileName: string): string {
  return `${FILE_ICON_PREFIX}${fileName}`
}

/** The URL an uploaded icon is loaded from in the renderer. */
export function iconFileUrl(fileName: string): string {
  return `${ICON_SCHEME}://icons/${fileName}`
}

/** Image types accepted for upload, as MIME type → file extension. */
export const ICON_UPLOAD_TYPES: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/gif': 'gif',
  'image/webp': 'webp',
  'image/svg+xml': 'svg'
}

/** 2 MB — a page icon renders at 64px at most; anything larger is a mistake. */
export const ICON_UPLOAD_MAX_BYTES = 2 * 1024 * 1024
